name: CI
on: push
jobs:
  pre-test:
    name: Check/Rustfmt/Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      # Workaround because clippy doesn't report any errors
      # if executed after cargo check
      - name: Clean
        uses: actions-rs/cargo@v1
        with:
          command: clean
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
